sed -i 's/%/@/g' bigCorners.lay    
sed -i 's/%/@/g' greedySearch.lay      
sed -i 's/%/@/g' mediumSearch.lay  
sed -i 's/%/@/g' smallMaze.lay
sed -i 's/%/@/g' tinyCorners.lay
sed -i 's/%/@/g' bigMaze.lay       
sed -i 's/%/@/g' mediumCorners.lay     
sed -i 's/%/@/g' oddSearch.lay     
sed -i 's/%/@/g' smallSearch.lay
sed -i 's/%/@/g' tinyMaze.lay
sed -i 's/%/@/g' bigSearch.lay     
sed -i 's/%/@/g' mediumDottedMaze.lay  
sed -i 's/%/@/g' openMaze.lay      
sed -i 's/%/@/g' testMaze.lay
sed -i 's/%/@/g' tinySearch.lay
sed -i 's/%/@/g' contoursMaze.lay  
sed -i 's/%/@/g' mediumMaze.lay        
sed -i 's/%/@/g' openSearch.lay    
sed -i 's/%/@/g' testSearch.lay
sed -i 's/%/@/g' trickySearch.lay
